### PR TITLE
Devx 5915 - Update .NET Server SDK for 1080p Archive/Broadcast

### PR DESCRIPTION
**Pull request by Tr00d**
Add all available resolutions on Readme, XML doc and Sample apps.
Resolutions were already handled in OpenTok.

### CODE REVIEW

**Review by jeffswartz — APPROVED** [review]
Approved, but should this PR target the dev branch, so that it can be combined into a build with other additions for 3.9.0?

**Comment by Tr00d** [comment]
@jeffswartz Sure, but I'll have to create a new PR for that. I don't think I can change the target branch just like that... I'll let you know

**Comment by Tr00d** [comment]
The new PR targeting dev can be found [here](https://github.com/opentok/Opentok-.NET-SDK/pull/207)
I'm closing this one.

**Comment by jeffswartz** [comment]
> @jeffswartz Sure, but I'll have to create a new PR for that. I don't think I can change the target branch just like that... I'll let you know

@Tr00d You can change the target branch of a PR by clicking the "Edit" button to the right of the title and changing the target branch. But you might need special privileges to do so. (As creator of the PR, you should be able to.)

**Pull request closed without merging**
